# Generated by Django 4.2.3 on 2023-07-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_background_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
