# Generated by Django 4.2.3 on 2023-07-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='about_summary',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='hero_background_img',
            field=models.ImageField(blank=True, null=True, upload_to='heroBackgroud'),
        ),
        migrations.AddField(
            model_name='home',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='social1_icon',
            field=models.ImageField(blank=True, null=True, upload_to='socials'),
        ),
        migrations.AddField(
            model_name='home',
            name='social1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='social2_icon',
            field=models.ImageField(blank=True, null=True, upload_to='socials'),
        ),
        migrations.AddField(
            model_name='home',
            name='social2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='social3_icon',
            field=models.ImageField(blank=True, null=True, upload_to='socials'),
        ),
        migrations.AddField(
            model_name='home',
            name='social3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='social4_icon',
            field=models.ImageField(blank=True, null=True, upload_to='socials'),
        ),
        migrations.AddField(
            model_name='home',
            name='social4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
