# Generated by Django 4.2.3 on 2023-07-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categories_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author_image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media_files/authorImg'),
        ),
        migrations.AddField(
            model_name='articles',
            name='lead_img_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media_files/blog'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(blank=True, default='wise m', max_length=200, null=True),
        ),
    ]
