# Generated by Django 4.2.3 on 2023-07-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articles_author_image_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(blank=True, max_length=100, null=True)),
                ('social_icon', models.ImageField(blank=True, null=True, upload_to='socials')),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='social1_icon',
        ),
        migrations.RemoveField(
            model_name='home',
            name='social1_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='social2_icon',
        ),
        migrations.RemoveField(
            model_name='home',
            name='social2_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='social3_icon',
        ),
        migrations.RemoveField(
            model_name='home',
            name='social3_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='social4_icon',
        ),
        migrations.RemoveField(
            model_name='home',
            name='social4_name',
        ),
        migrations.AlterField(
            model_name='home',
            name='about_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
