# Generated by Django 4.2.3 on 2023-07-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_socials_remove_home_social1_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socials',
            name='social_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
